OUTPUT_DIR: './HiGNN/test/tianran'
TAG: 'default'
SEED: 1
NUM_FOLDS: 10
HYPER: True
HYPER_REMOVE: None
NUM_ITERS: 30


DATA:
  BATCH_SIZE: 64
  DATASET: 'tianran'
  DATA_PATH: './HiGNN/data/tianran/'
  TASK_TYPE: 'classification'
  METRIC: 'auc'   # acc/auc/prc/rmse/mae
  SPLIT_TYPE: 'random'  # random/scaffold/noise
  RANDOM_NUM: 20
  

MODEL:
  F_ATT: False
  BRICS: False
  

LOSS:
  FL_LOSS: False
  CL_LOSS: False


TRAIN:
  EARLY_STOP: 50
  MAX_EPOCHS: 200
  OPTIMIZER:
    TYPE: 'adam'
  LR_SCHEDULER:
    TYPE: 'reduce'
