OUTPUT_DIR: './test/zhongliu'
TAG: 'default'
SEED: 2030
NUM_FOLDS: 10
HYPER: True
HYPER_REMOVE: None
NUM_ITERS: 30


DATA:
  BATCH_SIZE: 64
  DATASET: 'zhongliu'
  DATA_PATH: './data/zhongliu/'
  TASK_TYPE: 'classification'
  METRIC: 'auc'
  SPLIT_TYPE: 'random'
  RANDOM_NUM: 10


MODEL:
  F_ATT: False
  BRICS: False


LOSS:
  FL_LOSS: False
  CL_LOSS: False


TRAIN:
  EARLY_STOP: 50
  MAX_EPOCHS: 400
  OPTIMIZER:
    TYPE: 'adam'
  LR_SCHEDULER:
    TYPE: 'reduce'
