OUTPUT_DIR: './HiGNN/test/tox21'
TAG: 'default'
SEED: 1
NUM_FOLDS: 10
HYPER: True
HYPER_REMOVE: None
NUM_ITERS: 30


DATA:
  BATCH_SIZE: 32
  DATASET: 'tox21'
  DATA_PATH: './HiGNN/data/tox21/'
  TASK_TYPE: 'classification'
  METRIC: 'auc'
  SPLIT_TYPE: 'random'
  RANDOM_NUM: 1


MODEL:
  F_ATT: True
  BRICS: True


LOSS:
  FL_LOSS: False
  CL_LOSS: False


TRAIN:
  EARLY_STOP: 50
  MAX_EPOCHS: 100
  OPTIMIZER:
    TYPE: 'adam'
  LR_SCHEDULER:
    TYPE: 'reduce'
